### PR TITLE
Fix log_shiny_input_changes

### LINKED ISSUE #98: [Bug]: log_shiny_input_changes checks for session_proxy but session is ShinySession
### What happened?

When running interactively the example of `log_shiny_input_changes` I got an error message:

```r
Warning: Error in log_shiny_input_changes: inherits(session, "session_proxy") is not TRUE
  44: <Anonymous>
  43: stop
  42: stopifnot
  41: log_shiny_input_changes [C:/Users/sanchosl/AppData/Local/Temp/Rtmp2Z3KZu/R.INSTALL7ebc330b4754/teal.logger/R/log_shiny_input_changes.R#47]
  40: server [#2]
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
Error in log_shiny_input_changes(input, excluded_inputs = "password",  : 
  inherits(session, "session_proxy") is not TRUE
```

The check is testing for `session_proxy `but session is a `ShinySession`. Simply changing that would probably solve the issue (I don't see any mention in shiny about a session_proxy class). 

`logger::log_shiny_input_changes` checks for `session_proxy` too but there are some other checks and their example doesn't fail. The other checks:

```
(shiny::isRunning() || inherits(session, "MockShinySession") || 
        inherits(session, "session_proxy"))
``` 

### sessionInfo()

```R
─ Session info ────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.4.1 (2024-06-14 ucrt)
 os       Windows 11 x64 (build 22631)
 system   x86_64, mingw32
 ui       RStudio
 language en
 collate  Spanish_Spain.utf8
 ctype    Spanish_Spain.utf8
 tz       Europe/Madrid
 date     2024-11-06
 rstudio  2024.09.0+375 Cranberry Hibiscus (desktop)
 pandoc   3.5 @ C:\\Users\\sanchosl\\AppData\\Local\\Pandoc\\pandoc.exe

─ Packages ────────────────────────────────────────────────────────────────────
 ! package     * version    date (UTC) lib source
   brio          1.1.5      2024-04-24 [1] CRAN (R 4.4.1)
   bslib         0.8.0      2024-07-29 [1] CRAN (R 4.4.1)
   cachem        1.1.0      2024-05-16 [1] CRAN (R 4.4.1)
   cli           3.6.3      2024-06-21 [1] CRAN (R 4.4.1)
   crayon        1.5.3      2024-06-20 [1] CRAN (R 4.4.1)
   desc          1.4.3      2023-12-10 [1] CRAN (R 4.4.1)
   devtools    * 2.4.5      2022-10-11 [1] CRAN (R 4.4.1)
   digest        0.6.37     2024-08-19 [1] CRAN (R 4.4.1)
   ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.4.1)
   fansi         1.0.6      2023-12-08 [1] CRAN (R 4.4.1)
   fastmap       1.2.0      2024-05-15 [1] CRAN (R 4.4.1)
   fs            1.6.4      2024-04-25 [1] CRAN (R 4.4.1)
   glue          1.8.0      2024-09-30 [1] CRAN (R 4.4.1)
   htmltools     0.5.8.1    2024-04-04 [1] CRAN (R 4.4.1)
   htmlwidgets   1.6.4      2023-12-06 [1] CRAN (R 4.4.1)
   httpuv        1.6.15     2024-03-26 [1] CRAN (R 4.4.1)
   jquerylib     0.1.4      2021-04-26 [1] CRAN (R 4.4.1)
   jsonlite      1.8.9      2024-09-20 [1] CRAN (R 4.4.1)
   later         1.3.2      2023-12-06 [1] CRAN (R 4.4.1)
   lifecycle     1.0.4      2023-11-07 [1] CRAN (R 4.4.1)
   logger        0.4.0      2024-10-22 [1] CRAN (R 4.4.1)
   magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.4.1)
   memoise       2.0.1      2021-11-26 [1] CRAN (R 4.4.1)
   mime          0.12       2021-09-28 [1] CRAN (R 4.4.0)
   miniUI        0.1.1.1    2018-05-18 [1] CRAN (R 4.4.1)
   pillar        1.9.0      2023-03-22 [1] CRAN (R 4.4.1)
   pkgbuild      1.4.4      2024-03-17 [1] CRAN (R 4.4.1)
   pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.4.1)
   pkgload       1.4.0      2024-06-28 [1] CRAN (R 4.4.1)
   profvis       0.4.0      2024-09-20 [1] CRAN (R 4.4.1)
   promises      1.3.0      2024-04-05 [1] CRAN (R 4.4.1)
   purrr         1.0.2      2023-08-10 [1] CRAN (R 4.4.1)
   R6            2.5.1      2021-08-19 [1] CRAN (R 4.4.1)
   Rcpp          1.0.13     2024-07-17 [1] CRAN (R 4.4.1)
   remotes       2.5.0      2024-03-17 [1] CRAN (R 4.4.1)
   rlang         1.1.4      2024-06-04 [1] CRAN (R 4.4.1)
   rprojroot     2.0.4      2023-11-05 [1] CRAN (R 4.4.1)
   rstudioapi    0.17.1     2024-10-22 [1] CRAN (R 4.4.1)
   sass          0.4.9      2024-03-15 [1] CRAN (R 4.4.1)
   sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.4.1)
   shiny       * 1.9.1      2024-08-01 [1] CRAN (R 4.4.1)
 P teal.logger * 0.3.0.9000 2024-11-06 [?] load_all()
   testthat    * 3.2.1.1    2024-04-14 [1] CRAN (R 4.4.1)
   tibble        3.2.1      2023-03-20 [1] CRAN (R 4.4.1)
   urlchecker    1.0.1      2021-11-30 [1] CRAN (R 4.4.1)
   usethis     * 3.0.0      2024-07-29 [1] CRAN (R 4.4.1)
   utf8          1.2.4      2023-10-22 [1] CRAN (R 4.4.1)
   vctrs         0.6.5      2023-12-01 [1] CRAN (R 4.4.1)
   withr         3.0.2      2024-10-28 [1] CRAN (R 4.4.1)
   xtable        1.8-4      2019-04-21 [1] CRAN (R 4.4.1)

 [1] C:/Users/sanchosl/AppData/Local/R/win-library/4.4
 [2] C:/Program Files/R/R-4.4.1/library

 P ── Loaded and on-disk path mismatch.

───────────────────────────────────────────────────────────────────────────────
```

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by llrs-roche**
# Pull Request

This fixes the shiny app and also `log_shiny_input_changes` works now without error.

I took the liberty to "fix" and accept lower case teal.log_level, but I'm not sure if this is wanted or not.
At least it could provide an informative error message if a lower case is not accepted. 

Last, I see this logging:

```
TRACE from teal.logger [2024-11-06 13:34:17] :: character(0) Shiny input change detected in "foo": "foo" -> "fooa"
```

Note the `character(0)`, this is "{ns}"; but I don't see any assignment besides [making it 0 on line 54](https://github.com/insightsengineering/teal.logger/blob/cd9cc7e5be19c2417700308d6bdf1d8c4a55966d/R/log_shiny_input_changes.R#L54). So I am not sure if this should be replaced on the logger environment or here, but either case it could be more informative. 

Fixes #98

### CODE REVIEW

**Comment by llrs-roche** [comment]
I hadn't run any teal.gallery code yet. When I searched for any [log_shiny_input_changes in the repo](https://github.com/search?q=repo%3Ainsightsengineering%2Fteal.gallery%20log_shiny_input_changes&type=code) I didn't see any of them using it. 
But I am testing one ("efficacy") with the code in the README.md, as it is the first time I am rebuilding the renv (and it took some time but ultimately failed). 

Sorry, I saw the code about layout shared by Vedha and added it to my `~/.Renviron`, I disabled it now and tested again the example and now I don't see any message on the console.

**Comment by llrs-roche** [comment]
1) Verify which modules are affected by changes in `teal.logger::log_shiny_input_changes` on `teal.modules.clinical`:

<details>
<summary>Using flow</summary>


```r
library(flow)
library(teal.logger)
library(teal.modules.clinical)
flow_view_uses(log_shiny_input_changes, pkg = "teal.modules.clinical")
```
Basically many:
flow_shiny_log_teal modules clinical

</details>


2) Setting up teal.gallery/efficacy.Rproj

<details>
<summary>Configurations</summary>


Open the Rstudio, teal.gallery/efficacy/efficacy.Rproj folder:
 - The R version used is 4.3.2 I'm testing 4.4.1
 - The Bioconductor version used is 3.17 the corresponding for 4.3.2 but I'm using the latest (3.20)
 
```r
renv::restore()
renv::status()
The lockfile was generated with R 4.3.2, but you're using R 4.4.1.

See `?renv::status` for advice on resolving these issues.
```

</details>


3) Testing the changes

Disable RStudio R diagnostic options to [prevent attaching packages](https://forum.posit.co/t/prevent-rstudio-from-loading-namespaces-at-startup/158442/3). (Or use another IDE).
Restart Rstudio and open again the efficacy project.

```r
install.packages("devtools")
# While having the https://github.com/insightsengineering/teal.logger/tree/98_log_input branch set:
devtools::install("../../teal.logger")
```

<details>
<summary>Run the app</summary>


```r
getOption("TEAL.LOG_LAYOUT")
NULL
options(teal.log_level = "DEBUG")
```

```r
library(teal.modules.general)
library(teal.modules.clinical)
options(shiny.useragg = FALSE)

## Data reproducible code ----
data <- teal_data()
data <- within(data, {
  library(dplyr)
  library(random.cdisc.data)
  library(nestcolor)
  # optional libraries
  library(sparkline)

  ADSL <- radsl(seed = 1)
  adsl_labels <- teal.data::col_labels(ADSL, fill = FALSE)

  char_vars_asl <- names(Filter(isTRUE, sapply(ADSL, is.character)))

  adsl_labels <- c(
    adsl_labels,
    AGEGR1 = "Age Group"
  )
  ADSL <- ADSL %>%
    mutate(
      AGEGR1 = factor(case_when(
        AGE < 45 ~ "<45",
        AGE >= 45 ~ ">=45"
      ))
    ) %>%
    mutate_at(char_vars_asl, factor)

  teal.data::col_labels(ADSL) <- adsl_labels

  ADTTE <- radtte(ADSL, seed = 1)

  ADRS <- radrs(ADSL, seed = 1)
  adrs_labels <- teal.data::col_labels(ADRS, fill = FALSE)
  ADRS <- filter(ADRS, PARAMCD == "BESRSPI" | AVISIT == "FOLLOW UP")
  teal.data::col_labels(ADRS) <- adrs_labels

  ADQS <- radqs(ADSL, seed = 1)
  adqs_labels <- teal.data::col_labels(ADQS, fill = FALSE)
  ADQS <- ADQS %>%
    filter(ABLFL != "Y" & ABLFL2 != "Y") %>%
    filter(AVISIT %in% c("WEEK 1 DAY 8", "WEEK 2 DAY 15", "WEEK 3 DAY 22")) %>%
    mutate(
      AVISIT = as.factor(AVISIT),
      AVISITN = rank(AVISITN) %>%
        as.factor() %>%
        as.numeric() %>%
        as.factor()
    )
  teal.data::col_labels(ADQS) <- adqs_labels
})

# set datanames
datanames <- c("ADSL", "ADTTE", "ADRS", "ADQS")
datanames(data) <- datanames

# set join_keys
join_keys(data) <- default_cdisc_join_keys[datanames]

## Reusable Configuration For Modules
ADSL <- data[["ADSL"]]
ADTTE <- data[["ADTTE"]]
ADRS <- data[["ADRS"]]
ADQS <- data[["ADQS"]]
char_vars_asl <- data[["char_vars_asl"]]

arm_vars <- c("ARMCD", "ARM")
strata_vars <- c("STRATA1", "STRATA2")
facet_vars <- c("AGEGR1", "BMRKR2", "SEX", "COUNTRY")
cov_vars <- c("AGE", "SEX", "BMRKR1", "BMRKR2", "REGION1")
visit_vars <- c("AVISIT", "AVISITN")

cs_arm_var <- choices_selected(
  choices = variable_choices(ADSL, subset = arm_vars),
  selected = "ARM"
)

cs_strata_var <- choices_selected(
  choices = variable_choices(ADSL, subset = strata_vars),
  selected = "STRATA1"
)

cs_facet_var <- choices_selected(
  choices = variable_choices(ADSL, subset = facet_vars),
  selected = "AGEGR1"
)

cs_cov_var <- choices_selected(
  choices = variable_choices(ADSL, subset = cov_vars),
  selected = "AGE"
)

cs_paramcd_tte <- choices_selected(
  choices = value_choices(ADTTE, "PARAMCD", "PARAM"),
  selected = "OS"
)

cs_paramcd_rsp <- choices_selected(
  choices = value_choices(ADRS, "PARAMCD", "PARAM"),
  selected = "BESRSPI"
)

cs_paramcd_qs <- choices_selected(
  choices = value_choices(ADQS, "PARAMCD", "PARAM"),
  selected = "FKSI-FWB"
)

cs_visit_var_qs <- choices_selected(
  choices = variable_choices(ADQS, subset = visit_vars),
  selected = "AVISIT"
)

fact_vars_asl <- names(Filter(isTRUE, sapply(ADSL, is.factor)))
fact_vars_asl_orig <- fact_vars_asl[!fact_vars_asl %in% char_vars_asl]

date_vars_asl <- names(ADSL)[vapply(ADSL, function(x) inherits(x, c("Date", "POSIXct", "POSIXlt")), logical(1))]
demog_vars_asl <- names(ADSL)[!(names(ADSL) %in% c("USUBJID", "STUDYID", date_vars_asl))]

# reference & comparison arm selection when switching the arm variable
# ARMCD is given in a delayed fashion using value choices and
# ARM is given with the ref and comp levels supplied explicitly
arm_ref_comp <- list(
  ARMCD = list(
    ref = value_choices("ADSL", var_choices = "ARMCD", var_label = "ARM", subset = "ARM A"),
    comp = value_choices("ADSL", var_choices = "ARMCD", var_label = "ARM", subset = c("ARM B", "ARM C"))
  ),
  ARM = list(ref = "A: Drug X", comp = c("B: Placebo", "C: Combination"))
)

## App header and footer ----
nest_logo <- "https://raw.githubusercontent.com/insightsengineering/hex-stickers/main/PNG/nest.png"
app_source <- "https://github.com/insightsengineering/teal.gallery/tree/main/efficacy"
gh_issues_page <- "https://github.com/insightsengineering/teal.gallery/issues"

header <- tags$span(
  style = "display: flex; align-items: center; justify-content: space-between; margin: 10px 0 10px 0;",
  tags$span("My first teal app", style = "font-size: 30px;"),
  tags$span(
    style = "display: flex; align-items: center;",
    tags$img(src = nest_logo, alt = "NEST logo", height = "45px", style = "margin-right:10px;"),
    tags$span(style = "font-size: 24px;", "NEST @ Roche")
  )
)

footer <- tags$p(
  "This teal app is brought to you by the NEST Team at Roche/Genentech.
        For more information, please visit:",
  tags$a(href = app_source, target = "_blank", "Source Code"), ", ",
  tags$a(href = gh_issues_page, target = "_blank", "Report Issues")
)

## Setup App
app <- init(
  data = data,
  title = build_app_title("Efficacy Analysis Teal Demo App", nest_logo),
  header = header,
  footer = footer,
  filter = teal_slices(
    count_type = "all",
    teal_slice(dataname = "ADSL", varname = "ITTFL", selected = "Y"),
    teal_slice(dataname = "ADSL", varname = "SEX"),
    teal_slice(dataname = "ADSL", varname = "AGE")
  ),
  modules = modules(
    tm_front_page(
      label = "App Info",
      header_text = c(
        "Info about input data source" =
          "This app uses CDISC ADaM datasets randomly generated by `random.cdisc.data` R packages"
      ),
      tables = list(`NEST packages used in this demo app` = data.frame(
        Packages = c("teal.modules.general", "teal.modules.clinical", "random.cdisc.data")
      ))
    ),
    tm_data_table("Data Table"),
    tm_variable_browser("Variable Browser"),
    tm_t_summary(
      label = "Demographic Table",
      dataname = "ADSL",
      arm_var = cs_arm_var,
      summarize_vars = choices_selected(
        choices = variable_choices(ADSL, demog_vars_asl),
        selected = c("SEX", "AGE", "RACE")
      )
    ),
    modules(
      label = "Forest Plots",
      tm_g_forest_tte(
        label = "Survival Forest Plot",
        dataname = "ADTTE",
        arm_var = cs_arm_var,
        strata_var = cs_strata_var,
        subgroup_var = cs_facet_var,
        paramcd = cs_paramcd_tte,
        plot_height = c(800L, 200L, 4000L)
      ),
      tm_g_forest_rsp(
        label = "Response Forest Plot",
        dataname = "ADRS",
        arm_var = cs_arm_var,
        strata_var = cs_strata_var,
        subgroup_var = cs_facet_var,
        paramcd = cs_paramcd_rsp,
        plot_height = c(800L, 200L, 4000L)
      )
    ),
    tm_g_km(
      label = "Kaplan Meier Plot",
      dataname = "ADTTE",
      arm_var = cs_arm_var,
      arm_ref_comp = arm_ref_comp,
      paramcd = cs_paramcd_tte,
      facet_var = cs_facet_var,
      strata_var = cs_strata_var,
      plot_height = c(1800L, 200L, 4000L)
    ),
    tm_t_binary_outcome(
      label = "Response Table",
      dataname = "ADRS",
      arm_var = cs_arm_var,
      arm_ref_comp = arm_ref_comp,
      paramcd = cs_paramcd_rsp,
      strata_var = cs_strata_var,
      rsp_table = TRUE
    ),
    tm_t_tte(
      label = "Time To Event Table",
      dataname = "ADTTE",
      arm_var = cs_arm_var,
      paramcd = cs_paramcd_tte,
      strata_var = cs_strata_var,
      time_points = choices_selected(c(182, 365, 547), 182),
      event_desc_var = choices_selected(
        choices = variable_choices("ADTTE", "EVNTDESC"),
        selected = "EVNTDESC",
        fixed = TRUE
      )
    ),
    tm_t_crosstable(
      "Cross Table",
      x = data_extract_spec(
        dataname = "ADSL",
        select = select_spec(
          choices = variable_choices(ADSL, fact_vars_asl_orig),
          selected = fact_vars_asl_orig[1]
        )
      ),
      y = data_extract_spec(
        dataname = "ADSL",
        select = select_spec(
          choices = variable_choices(ADSL, fact_vars_asl_orig),
          selected = fact_vars_asl_orig[4]
        )
      )
    ),
    tm_t_coxreg(
      label = "Cox Reg",
      dataname = "ADTTE",
      arm_var = cs_arm_var,
      arm_ref_comp = arm_ref_comp,
      paramcd = cs_paramcd_tte,
      strata_var = cs_strata_var,
      cov_var = cs_cov_var
    ),
    tm_t_logistic(
      label = "Logistic Reg",
      dataname = "ADRS",
      arm_var = cs_arm_var,
      arm_ref_comp = NULL,
      paramcd = cs_paramcd_rsp,
      cov_var = cs_cov_var
    ),
    tm_a_mmrm(
      label = "MMRM",
      dataname = "ADQS",
      aval_var = choices_selected(c("AVAL", "CHG"), "AVAL"),
      id_var = choices_selected(c("USUBJID", "SUBJID"), "USUBJID"),
      arm_var = cs_arm_var,
      visit_var = cs_visit_var_qs,
      arm_ref_comp = arm_ref_comp,
      paramcd = cs_paramcd_qs,
      cov_var = choices_selected(c("BASE", "AGE", "SEX", "BASE:AVISIT"), NULL),
      conf_level = choices_selected(c(0.95, 0.9, 0.8), 0.95)
    ),
    tm_t_binary_outcome(
      label = "Binary Response",
      dataname = "ADRS",
      arm_var = cs_arm_var,
      paramcd = cs_paramcd_rsp,
      strata_var = cs_strata_var
    ),
    tm_t_ancova(
      label = "ANCOVA",
      dataname = "ADQS",
      avisit = choices_selected(value_choices(ADQS, "AVISIT"), "WEEK 1 DAY 8"),
      arm_var = cs_arm_var,
      arm_ref_comp = arm_ref_comp,
      aval_var = choices_selected(variable_choices(ADQS, c("AVAL", "CHG", "PCHG")), "CHG"),
      cov_var = choices_selected(variable_choices(ADQS, c("BASE", "STRATA1", "SEX")), "STRATA1"),
      paramcd = cs_paramcd_qs
    )
  )
)

shinyApp(app$ui, app$server)
```

</details>

The only output after changing the input of the Cox Reg tab is:

```
Listening on http://127.0.0.1:4674
[INFO] 2024-11-07 10:01:29.1082 pid:31036 token:[02a72d60] teal Initializing reporter_previewer_module
mmrm() registered as emmeans extension
Warning: The 'plotly_relayout' event tied a source ID of 'teal-main_ui-filter_panel-active-ADSL-filter-ADSL_AGE-inputs-histogram_plot' is not registered. In order to obtain this event data, please add `event_register(p, 'plotly_relayout')` to the plot (`p`) that you wish to obtain event data from.

```

# teal.log_level = "trace"

library("teal.modules.general") doesn't handle lowercase (from a fresh new R session): 

<details>
<summary>Log</summary>

```r
> getOption("TEAL.LOG_LAYOUT")
NULL
> options(teal.log_level = "trace")
> library(teal.modules.general)
Loading required package: ggmosaic
Loading required package: ggplot2
Loading required package: shiny
Loading required package: teal
Loading required package: teal.data
Loading required package: teal.code
Loading required package: teal.slice
Error: package or namespace load failed for ‘teal.slice’:
 .onLoad failed in loadNamespace() for 'teal.slice', details:
  call: NULL
  error: .onLoad failed in loadNamespace() for 'teal.logger', details:
  call: value[[3L]](cond)
  error: The log level passed to logger::log_threshold was invalid. Make sure you pass or set the correct log level. See `logger::log_threshold` for more information
Error: package ‘teal.slice’ could not be loaded
```

</details>

Message too long, I'll continue in a new comment

**Comment by llrs-roche** [comment]
# teal.log_level = TRACE

With level TRACE and the above app I see plenty of logging (from a fresh R session with the same app as above).
I modified the Cox Reg tab and went to other tabs.

```r
getOption("TEAL.LOG_LAYOUT")
NULL
options(teal.log_level = "TRACE")
```

<details>
<summary>Log</summary>

```r
[TRACE] 2024-11-07 10:11:46.1699 pid:25200 token:[] teal init initializing teal app with: data ('structure("teal_data", package = "teal.data")').
[INFO] 2024-11-07 10:11:46.1836 pid:25200 token:[] teal.modules.general Initializing tm_front_page
[INFO] 2024-11-07 10:11:46.1903 pid:25200 token:[] teal.modules.general Initializing tm_data_table
[INFO] 2024-11-07 10:11:46.1972 pid:25200 token:[] teal.modules.general Initializing tm_variable_browser
Initializing tm_t_summary
Initializing tm_g_forest_tte
Initializing tm_g_forest_rsp
Initializing tm_g_km
Initializing tm_t_binary_outcome
Initializing tm_t_tte
[INFO] 2024-11-07 10:11:46.3156 pid:25200 token:[] teal.modules.general Initializing tm_t_crosstable
Initializing tm_t_coxreg
Initializing tm_t_logistic
Initializing tm_a_mmrm
Initializing tm_t_binary_outcome
Initializing tm_t_ancova
[TRACE] 2024-11-07 10:11:46.5338 pid:25200 token:[] teal.logger Platform: "x86_64-w64-mingw32/x64"
[TRACE] 2024-11-07 10:11:46.5374 pid:25200 token:[] teal.logger Running under: "Windows 11 x64 (build 22631)"
[TRACE] 2024-11-07 10:11:46.5433 pid:25200 token:[] teal.logger "R version 4.4.1 (2024-06-14 ucrt)"
[TRACE] 2024-11-07 10:11:46.5492 pid:25200 token:[] teal.logger Base packages: "stats graphics grDevices datasets utils methods base"
[TRACE] 2024-11-07 10:11:46.6005 pid:25200 token:[] teal.logger Other attached packages: "sparkline 2.0, nestcolor 0.1.2.9017, random.cdisc.data 0.3.16, dplyr 1.1.4, teal.modules.clinical 0.9.1, tern 0.9.6, rtables 0.6.10, magrittr 2.0.3, formatters 0.5.9, teal.modules.general 0.3.0, teal.transform 0.5.0, teal 0.15.2, teal.slice 0.5.1, teal.data 0.6.0, teal.code 0.5.0, shiny 1.9.1, ggmosaic 0.3.3, ggplot2 3.5.1"
[TRACE] 2024-11-07 10:11:46.7030 pid:25200 token:[] teal.logger Loaded packages: "gtable 0.3.6, teal.widgets 0.4.2, htmlwidgets 1.6.4, ggrepel 0.9.6, lattice 0.22.6, vctrs 0.6.5, tools 4.4.1, Rdpack 2.6.1, generics 0.1.3, tibble 3.2.1, fansi 1.0.6, pkgconfig 2.0.3, Matrix 1.6.5, data.table 1.16.2, checkmate 2.3.2, lifecycle 1.0.4, stringr 1.5.1, compiler 4.4.1, munsell 0.5.1, httpuv 1.6.15, htmltools 0.5.8.1, yaml 2.3.10, lazyeval 0.2.2, plotly 4.10.4, later 1.3.2, pillar 1.9.0, tidyr 1.3.1, MASS 7.3.60.0.1, tern.gee 0.1.5, nlme 3.1.166, mime 0.12, tidyselect 1.2.1, digest 0.6.37, mvtnorm 1.3.2, stringi 1.8.4, purrr 1.0.2, geepack 1.3.12, splines 4.4.1, fastmap 1.2.0, grid 4.4.1, colorspace 2.1.1, cli 3.6.3, logger 0.4.0, survival 3.7.0, utf8 1.2.4, broom 1.0.7, withr 3.0.2, scales 1.3.0, promises 1.3.0, backports 1.5.0, timechange 0.3.0, lubridate 1.9.3, estimability 1.5.1, httr 1.4.7, emmeans 1.10.5, rbibutils 2.3, viridisLite 0.4.2, rlang 1.1.4, Rcpp 1.0.13.1, xtable 1.8.4, glue 1.8.0, renv 1.0.11, rstudioapi 0.17.1, jsonlite 1.8.9, teal.logger 0.3.0.9000, R6 2.5.1"
[TRACE] 2024-11-07 10:11:46.9204 pid:25200 token:[] teal init teal app has been initialized.
> 
> shinyApp(app$ui, app$server)

Listening on http://127.0.0.1:3487
[TRACE] 2024-11-07 10:11:48.8582 pid:25200 token:[3feda1ab] teal srv_teal_with_splash initializing module with data.
[TRACE] 2024-11-07 10:11:48.9691 pid:25200 token:[3feda1ab] teal srv_teal initializing the module.
[INFO] 2024-11-07 10:11:49.1848 pid:25200 token:[3feda1ab] teal Initializing reporter_previewer_module
[TRACE] 2024-11-07 10:11:49.1975 pid:25200 token:[3feda1ab] teal srv_teal_with_splash initialized module with data.
[TRACE] 2024-11-07 10:11:49.2962 pid:25200 token:[3feda1ab] teal.slice FilteredData$set_dataset setting dataset, name: "ADSL"
[TRACE] 2024-11-07 10:11:49.3148 pid:25200 token:[3feda1ab] teal.slice Instantiating "DataframeFilteredDataset", dataname: "ADSL"
[TRACE] 2024-11-07 10:11:49.3247 pid:25200 token:[3feda1ab] teal.slice Instantiating "DataframeFilteredDataset", dataname: "ADSL"
[TRACE] 2024-11-07 10:11:49.3409 pid:25200 token:[3feda1ab] teal.slice Instantiated "DataframeFilteredDataset", dataname: "ADSL"
[TRACE] 2024-11-07 10:11:49.3578 pid:25200 token:[3feda1ab] teal.slice Instantiating "DFFilterStates", dataname: "ADSL"
[TRACE] 2024-11-07 10:11:49.3668 pid:25200 token:[3feda1ab] teal.slice Instantiated "DFFilterStates", dataname: "ADSL"
[TRACE] 2024-11-07 10:11:49.3809 pid:25200 token:[3feda1ab] teal.slice FilteredData$set_dataset setting dataset, name: "ADTTE"
[TRACE] 2024-11-07 10:11:49.4173 pid:25200 token:[3feda1ab] teal.slice Instantiating "DataframeFilteredDataset", dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:49.4311 pid:25200 token:[3feda1ab] teal.slice Instantiating "DataframeFilteredDataset", dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:49.4455 pid:25200 token:[3feda1ab] teal.slice Instantiated "DataframeFilteredDataset", dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:49.4598 pid:25200 token:[3feda1ab] teal.slice Instantiating "DFFilterStates", dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:49.4653 pid:25200 token:[3feda1ab] teal.slice Instantiated "DFFilterStates", dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:49.4829 pid:25200 token:[3feda1ab] teal.slice filtering data dataname: "ADSL", sid: ""
[TRACE] 2024-11-07 10:11:49.4932 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:11:49.4986 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:11:49.5137 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:11:49.5346 pid:25200 token:[3feda1ab] teal.slice "DataframeFilteredDataset"$set_filter_state initializing, dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:49.5443 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates"$set_filter_state initializing, dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:49.5515 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates"$set_filter_state initialized, dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:49.5632 pid:25200 token:[3feda1ab] teal.slice FilteredData$set_dataset setting dataset, name: "ADRS"
[TRACE] 2024-11-07 10:11:49.5978 pid:25200 token:[3feda1ab] teal.slice Instantiating "DataframeFilteredDataset", dataname: "ADRS"
[TRACE] 2024-11-07 10:11:49.6050 pid:25200 token:[3feda1ab] teal.slice Instantiating "DataframeFilteredDataset", dataname: "ADRS"
[TRACE] 2024-11-07 10:11:49.6172 pid:25200 token:[3feda1ab] teal.slice Instantiated "DataframeFilteredDataset", dataname: "ADRS"
[TRACE] 2024-11-07 10:11:49.6314 pid:25200 token:[3feda1ab] teal.slice Instantiating "DFFilterStates", dataname: "ADRS"
[TRACE] 2024-11-07 10:11:49.6464 pid:25200 token:[3feda1ab] teal.slice Instantiated "DFFilterStates", dataname: "ADRS"
[TRACE] 2024-11-07 10:11:49.6596 pid:25200 token:[3feda1ab] teal.slice "DataframeFilteredDataset"$set_filter_state initializing, dataname: "ADRS"
[TRACE] 2024-11-07 10:11:49.6645 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates"$set_filter_state initializing, dataname: "ADRS"
[TRACE] 2024-11-07 10:11:49.6788 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates"$set_filter_state initialized, dataname: "ADRS"
[TRACE] 2024-11-07 10:11:49.6845 pid:25200 token:[3feda1ab] teal.slice FilteredData$set_dataset setting dataset, name: "ADQS"
[TRACE] 2024-11-07 10:11:49.7174 pid:25200 token:[3feda1ab] teal.slice Instantiating "DataframeFilteredDataset", dataname: "ADQS"
[TRACE] 2024-11-07 10:11:49.7280 pid:25200 token:[3feda1ab] teal.slice Instantiating "DataframeFilteredDataset", dataname: "ADQS"
[TRACE] 2024-11-07 10:11:49.7420 pid:25200 token:[3feda1ab] teal.slice Instantiated "DataframeFilteredDataset", dataname: "ADQS"
[TRACE] 2024-11-07 10:11:49.7529 pid:25200 token:[3feda1ab] teal.slice Instantiating "DFFilterStates", dataname: "ADQS"
[TRACE] 2024-11-07 10:11:49.7633 pid:25200 token:[3feda1ab] teal.slice Instantiated "DFFilterStates", dataname: "ADQS"
[TRACE] 2024-11-07 10:11:49.7781 pid:25200 token:[3feda1ab] teal.slice "DataframeFilteredDataset"$set_filter_state initializing, dataname: "ADQS"
[TRACE] 2024-11-07 10:11:49.7863 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates"$set_filter_state initializing, dataname: "ADQS"
[TRACE] 2024-11-07 10:11:49.7985 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates"$set_filter_state initialized, dataname: "ADQS"
[TRACE] 2024-11-07 10:11:49.9298 pid:25200 token:[3feda1ab] teal.slice "FilteredData"$set_filter_state initializing
[TRACE] 2024-11-07 10:11:49.9406 pid:25200 token:[3feda1ab] teal.slice "DataframeFilteredDataset"$set_filter_state initializing, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:49.9477 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates"$set_filter_state initializing, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:49.9768 pid:25200 token:[3feda1ab] teal.slice Instantiated FilterState object id: "ADSL ITTFL"
[TRACE] 2024-11-07 10:11:49.9871 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$set_selected setting selection of id: ADSL ITTFL
[TRACE] 2024-11-07 10:11:50.0032 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$set_selected selection of id: ADSL ITTFL
[TRACE] 2024-11-07 10:11:50.0096 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates" pushing into state_list, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:50.0288 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates" pushed into queue, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:50.0427 pid:25200 token:[3feda1ab] teal.slice Instantiated FilterState object id: "ADSL SEX"
[TRACE] 2024-11-07 10:11:50.0577 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$set_selected setting selection of id: ADSL SEX
[TRACE] 2024-11-07 10:11:50.0682 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$set_selected selection of id: ADSL SEX
[TRACE] 2024-11-07 10:11:50.0758 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates" pushing into state_list, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:50.0907 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates" pushed into queue, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:50.1163 pid:25200 token:[3feda1ab] teal.slice Instantiated FilterState object id: "ADSL AGE"
[TRACE] 2024-11-07 10:11:50.1321 pid:25200 token:[3feda1ab] teal.slice RangeFilterState$set_selected setting selection of id: ADSL AGE
[TRACE] 2024-11-07 10:11:50.1453 pid:25200 token:[3feda1ab] teal.slice RangeFilterState$set_selected selection of id: ADSL AGE
[TRACE] 2024-11-07 10:11:50.2471 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates" pushing into state_list, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:50.2534 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates" pushed into queue, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:50.2570 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates"$set_filter_state initialized, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:50.2638 pid:25200 token:[3feda1ab] teal.slice "DataframeFilteredDataset"$set_filter_state initializing, dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:50.3024 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates"$set_filter_state initializing, dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:50.3053 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates"$set_filter_state initialized, dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:50.3083 pid:25200 token:[3feda1ab] teal.slice "DataframeFilteredDataset"$set_filter_state initializing, dataname: "ADRS"
[TRACE] 2024-11-07 10:11:50.3109 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates"$set_filter_state initializing, dataname: "ADRS"
[TRACE] 2024-11-07 10:11:50.3158 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates"$set_filter_state initialized, dataname: "ADRS"
[TRACE] 2024-11-07 10:11:50.3229 pid:25200 token:[3feda1ab] teal.slice "DataframeFilteredDataset"$set_filter_state initializing, dataname: "ADQS"
[TRACE] 2024-11-07 10:11:50.3285 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates"$set_filter_state initializing, dataname: "ADQS"
[TRACE] 2024-11-07 10:11:50.3320 pid:25200 token:[3feda1ab] teal.slice "DFFilterStates"$set_filter_state initialized, dataname: "ADQS"
[TRACE] 2024-11-07 10:11:50.3354 pid:25200 token:[3feda1ab] teal.slice "FilteredData"$set_filter_state initialized
[TRACE] 2024-11-07 10:11:50.3398 pid:25200 token:[3feda1ab] teal srv_teal@5 setting main ui after data was pulled
mmrm() registered as emmeans extension
[TRACE] 2024-11-07 10:11:52.7416 pid:25200 token:[3feda1ab] teal srv_tabs_with_filters initializing the module.
[TRACE] 2024-11-07 10:11:52.7481 pid:25200 token:[3feda1ab] teal filter_manager_srv initializing for: "App Info, Data Table, Variable Browser, Demographic Table, Forest Plots, Kaplan Meier Plot, Response Table, Time To Event Table, Cross Table, Cox Reg, Logistic Reg, MMRM, Binary Response, ANCOVA, Report previewer".
[TRACE] 2024-11-07 10:11:52.8154 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_modules initializing the module "\"root\"".
[TRACE] 2024-11-07 10:11:52.8204 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"App Info\"".
[TRACE] 2024-11-07 10:11:52.8324 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"Data Table\"".
[TRACE] 2024-11-07 10:11:52.8451 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"Variable Browser\"".
[TRACE] 2024-11-07 10:11:52.8596 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"Demographic Table\"".
[TRACE] 2024-11-07 10:11:52.8753 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_modules initializing the module "\"Forest Plots\"".
[TRACE] 2024-11-07 10:11:52.8783 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"Survival Forest Plot\"".
[TRACE] 2024-11-07 10:11:52.8898 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"Response Forest Plot\"".
[TRACE] 2024-11-07 10:11:52.9060 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"Kaplan Meier Plot\"".
[TRACE] 2024-11-07 10:11:52.9194 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"Response Table\"".
[TRACE] 2024-11-07 10:11:52.9333 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"Time To Event Table\"".
[TRACE] 2024-11-07 10:11:52.9456 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"Cross Table\"".
[TRACE] 2024-11-07 10:11:52.9632 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"Cox Reg\"".
[TRACE] 2024-11-07 10:11:52.9763 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"Logistic Reg\"".
[TRACE] 2024-11-07 10:11:52.9870 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"MMRM\"".
[TRACE] 2024-11-07 10:11:53.0044 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"Binary Response\"".
[TRACE] 2024-11-07 10:11:53.0143 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"ANCOVA\"".
[TRACE] 2024-11-07 10:11:53.0242 pid:25200 token:[3feda1ab] teal srv_nested_tabs.teal_module initializing the module: "\"Report previewer\"".
[TRACE] 2024-11-07 10:11:53.0475 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_filter_panel initializing
[TRACE] 2024-11-07 10:11:53.0515 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_filter_overview initializing
[TRACE] 2024-11-07 10:11:53.0586 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_filter_overview initialized
[TRACE] 2024-11-07 10:11:53.0615 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_active initializing
[TRACE] 2024-11-07 10:11:53.0782 pid:25200 token:[3feda1ab] teal.slice FilteredDataset$srv_active initializing, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:53.0866 pid:25200 token:[3feda1ab] teal.slice FilterState$srv_active initializing, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:53.1004 pid:25200 token:[3feda1ab] teal.slice FilteredDataset$initialized, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:53.1041 pid:25200 token:[3feda1ab] teal.slice FilteredDataset$srv_active initializing, dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:53.1101 pid:25200 token:[3feda1ab] teal.slice FilterState$srv_active initializing, dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:53.1242 pid:25200 token:[3feda1ab] teal.slice FilteredDataset$initialized, dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:53.1276 pid:25200 token:[3feda1ab] teal.slice FilteredDataset$srv_active initializing, dataname: "ADRS"
[TRACE] 2024-11-07 10:11:53.1334 pid:25200 token:[3feda1ab] teal.slice FilterState$srv_active initializing, dataname: "ADRS"
[TRACE] 2024-11-07 10:11:53.1487 pid:25200 token:[3feda1ab] teal.slice FilteredDataset$initialized, dataname: "ADRS"
[TRACE] 2024-11-07 10:11:53.1519 pid:25200 token:[3feda1ab] teal.slice FilteredDataset$srv_active initializing, dataname: "ADQS"
[TRACE] 2024-11-07 10:11:53.1574 pid:25200 token:[3feda1ab] teal.slice FilterState$srv_active initializing, dataname: "ADQS"
[TRACE] 2024-11-07 10:11:53.1713 pid:25200 token:[3feda1ab] teal.slice FilteredDataset$initialized, dataname: "ADQS"
[TRACE] 2024-11-07 10:11:53.1776 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_active initialized
[TRACE] 2024-11-07 10:11:53.1806 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_add initializing
[TRACE] 2024-11-07 10:11:53.1867 pid:25200 token:[3feda1ab] teal.slice MAEFilteredDataset$srv_add initializing, dataname: "\"ADSL\""
[TRACE] 2024-11-07 10:11:53.1900 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_add initializing, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:53.1981 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_add initialized, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:53.2010 pid:25200 token:[3feda1ab] teal.slice MAEFilteredDataset$srv_add initialized, dataname: "\"ADSL\""
[TRACE] 2024-11-07 10:11:53.2045 pid:25200 token:[3feda1ab] teal.slice MAEFilteredDataset$srv_add initializing, dataname: "\"ADTTE\""
[TRACE] 2024-11-07 10:11:53.2090 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_add initializing, dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:53.2173 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_add initialized, dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:53.2202 pid:25200 token:[3feda1ab] teal.slice MAEFilteredDataset$srv_add initialized, dataname: "\"ADTTE\""
[TRACE] 2024-11-07 10:11:53.2235 pid:25200 token:[3feda1ab] teal.slice MAEFilteredDataset$srv_add initializing, dataname: "\"ADRS\""
[TRACE] 2024-11-07 10:11:53.2270 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_add initializing, dataname: "ADRS"
[TRACE] 2024-11-07 10:11:53.2351 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_add initialized, dataname: "ADRS"
[TRACE] 2024-11-07 10:11:53.2398 pid:25200 token:[3feda1ab] teal.slice MAEFilteredDataset$srv_add initialized, dataname: "\"ADRS\""
[TRACE] 2024-11-07 10:11:53.2454 pid:25200 token:[3feda1ab] teal.slice MAEFilteredDataset$srv_add initializing, dataname: "\"ADQS\""
[TRACE] 2024-11-07 10:11:53.2488 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_add initializing, dataname: "ADQS"
[TRACE] 2024-11-07 10:11:53.2569 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_add initialized, dataname: "ADQS"
[TRACE] 2024-11-07 10:11:53.2597 pid:25200 token:[3feda1ab] teal.slice MAEFilteredDataset$srv_add initialized, dataname: "\"ADQS\""
[TRACE] 2024-11-07 10:11:53.2619 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_filter_panel initialized
[TRACE] 2024-11-07 10:11:53.2649 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_filter_panel initialized
[TRACE] 2024-11-07 10:11:53.2721 pid:25200 token:[3feda1ab] teal srv_tabs_with_filters initialized the module
[TRACE] 2024-11-07 10:11:53.2780 pid:25200 token:[3feda1ab] teal filter_manager_srv@1 detecting states deltas in module: "global_filters".
[TRACE] 2024-11-07 10:11:53.4086 pid:25200 token:[3feda1ab] teal srv_teal@1 Timezone set to client's timezone: "Europe/Madrid".
[TRACE] 2024-11-07 10:11:53.5027 pid:25200 token:[3feda1ab] teal.slice filtering data dataname: "ADSL", sid: ""
[TRACE] 2024-11-07 10:11:53.5140 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:11:53.5253 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:11:53.5325 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:11:53.5359 pid:25200 token:[3feda1ab] teal.slice filtering data dataname: "ADTTE", sid: ""
[TRACE] 2024-11-07 10:11:53.5393 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:53.5429 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:11:53.5473 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:53.5540 pid:25200 token:[3feda1ab] teal.slice filtering data dataname: "ADRS", sid: ""
[TRACE] 2024-11-07 10:11:53.5578 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADRS"
[TRACE] 2024-11-07 10:11:53.5602 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:11:53.5625 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADRS"
[TRACE] 2024-11-07 10:11:53.5680 pid:25200 token:[3feda1ab] teal.slice filtering data dataname: "ADQS", sid: ""
[TRACE] 2024-11-07 10:11:53.5715 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADQS"
[TRACE] 2024-11-07 10:11:53.5742 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:11:53.5778 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADQS"
[TRACE] 2024-11-07 10:11:53.5876 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_filter_overview@1 updating counts
[TRACE] 2024-11-07 10:11:53.5938 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_active@1 determining added and removed filter states
[TRACE] 2024-11-07 10:11:53.6257 pid:25200 token:[3feda1ab] teal.slice filtering data dataname: "ADSL", sid: "ADSL ITTFL"
[TRACE] 2024-11-07 10:11:53.6284 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:11:53.6305 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:11:53.6371 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:11:53.6582 pid:25200 token:[3feda1ab] teal.slice filtering data dataname: "ADSL", sid: "ADSL SEX"
[TRACE] 2024-11-07 10:11:53.7317 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:11:53.7345 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:11:53.7418 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:11:53.8110 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_active@1 determining added and removed filter states
[TRACE] 2024-11-07 10:11:53.8170 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_active@1 determining added and removed filter states
[TRACE] 2024-11-07 10:11:53.8239 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_active@1 determining added and removed filter states
[TRACE] 2024-11-07 10:11:53.8297 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_add@1 updating available column choices, dataname: "ADSL"
[TRACE] 2024-11-07 10:11:53.8780 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_add@1 updating available column choices, dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:53.9048 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_add@1 updating available column choices, dataname: "ADRS"
[TRACE] 2024-11-07 10:11:53.9319 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_add@1 updating available column choices, dataname: "ADQS"
[TRACE] 2024-11-07 10:11:54.0079 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:11:54.0100 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:11:54.0156 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:11:54.0230 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:54.0261 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:11:54.0297 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADTTE"
[TRACE] 2024-11-07 10:11:54.0323 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADRS"
[TRACE] 2024-11-07 10:11:54.0345 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:11:54.0369 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADRS"
[TRACE] 2024-11-07 10:11:54.0393 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADQS"
[TRACE] 2024-11-07 10:11:54.0412 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:11:54.0439 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADQS"
[TRACE] 2024-11-07 10:11:54.0844 pid:25200 token:[3feda1ab] teal.slice FilterStates$srv_active@2 triggered by added states: "ADSL ITTFL, ADSL SEX, ADSL AGE"
[TRACE] 2024-11-07 10:11:54.0907 pid:25200 token:[3feda1ab] teal.slice FilterState$server initializing module for slice: "ADSL ITTFL" 
[TRACE] 2024-11-07 10:11:54.0995 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$server_inputs initializing, id: "ADSL ITTFL"
[TRACE] 2024-11-07 10:11:54.1182 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$server_inputs initialized, id: "ADSL ITTFL"
[TRACE] 2024-11-07 10:11:54.1342 pid:25200 token:[3feda1ab] teal.slice FilterState$server initializing module for slice: "ADSL SEX" 
[TRACE] 2024-11-07 10:11:54.1427 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$server_inputs initializing, id: "ADSL SEX"
[TRACE] 2024-11-07 10:11:54.1605 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$server_inputs initialized, id: "ADSL SEX"
[TRACE] 2024-11-07 10:11:54.1756 pid:25200 token:[3feda1ab] teal.slice FilterState$server initializing module for slice: "ADSL AGE" 
[TRACE] 2024-11-07 10:11:54.1834 pid:25200 token:[3feda1ab] teal.slice RangeFilterState$server initializing, id: "ADSL AGE"
[TRACE] 2024-11-07 10:11:54.2137 pid:25200 token:[3feda1ab] teal.slice RangeFilterState$server initialized, id: "ADSL AGE"
[TRACE] 2024-11-07 10:11:54.2395 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$server@1 state changed, id: "ADSL ITTFL"
[TRACE] 2024-11-07 10:11:54.2601 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$server@1 state changed, id: "ADSL SEX"
Warning: The 'plotly_relayout' event tied a source ID of 'teal-main_ui-filter_panel-active-ADSL-filter-ADSL_AGE-inputs-histogram_plot' is not registered. In order to obtain this event data, please add `event_register(p, 'plotly_relayout')` to the plot (`p`) that you wish to obtain event data from.
[TRACE] 2024-11-07 10:11:55.1384 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$server_inputs@2 changed selection, id: "ADSL ITTFL"
[TRACE] 2024-11-07 10:11:55.1416 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$set_selected setting selection of id: ADSL ITTFL
[TRACE] 2024-11-07 10:11:55.1455 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$set_selected selection of id: ADSL ITTFL
[TRACE] 2024-11-07 10:11:55.1496 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$server_inputs@2 changed selection, id: "ADSL SEX"
[TRACE] 2024-11-07 10:11:55.1529 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$set_selected setting selection of id: ADSL SEX
[TRACE] 2024-11-07 10:11:55.1579 pid:25200 token:[3feda1ab] teal.slice ChoicesFilterState$set_selected selection of id: ADSL SEX
[TRACE] 2024-11-07 10:12:25.6702 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:12:25.6740 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:12:25.6831 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:12:25.6877 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADTTE"
[TRACE] 2024-11-07 10:12:25.6913 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:12:25.6954 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADTTE"
[TRACE] 2024-11-07 10:12:25.7598 pid:25200 token:[3feda1ab] teal.transform data_extract_multiple_srv.list initialized with dataset: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:25.7725 pid:25200 token:[3feda1ab] teal.transform merge_expression_srv initialized with: "ADSL, ADTTE" datasets.
[TRACE] 2024-11-07 10:12:25.9121 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:25.9192 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADSL".
[TRACE] 2024-11-07 10:12:25.9347 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADSL" dataset.
[TRACE] 2024-11-07 10:12:25.9565 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:25.9650 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADTTE".
[TRACE] 2024-11-07 10:12:25.9725 pid:25200 token:[3feda1ab] teal.transform data_extract_filter_srv initialized with: "ADTTE" dataset.
[TRACE] 2024-11-07 10:12:25.9967 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADTTE" dataset.
[TRACE] 2024-11-07 10:12:26.0131 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:26.0186 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADSL".
[TRACE] 2024-11-07 10:12:26.0388 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADSL" dataset.
[TRACE] 2024-11-07 10:12:26.0639 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:26.0711 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADTTE".
[TRACE] 2024-11-07 10:12:26.0899 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADTTE" dataset.
[TRACE] 2024-11-07 10:12:26.1069 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:26.1122 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADTTE".
[TRACE] 2024-11-07 10:12:26.1305 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADTTE" dataset.
[TRACE] 2024-11-07 10:12:26.1628 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:26.1681 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADSL".
[TRACE] 2024-11-07 10:12:26.1871 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADSL" dataset.
[TRACE] 2024-11-07 10:12:26.2031 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADSL"; select: "ARM".
[TRACE] 2024-11-07 10:12:26.2075 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADSL"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:26.2139 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@1 dataname: "ADTTE"; filter vars: "PARAMCD"; filter values: "OS"
[TRACE] 2024-11-07 10:12:26.2213 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADTTE"; select: "PARAMCD".
[TRACE] 2024-11-07 10:12:26.2257 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADTTE"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:26.2342 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADSL"; select: "STRATA1".
[TRACE] 2024-11-07 10:12:26.2397 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADSL"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:26.2502 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADTTE"; select: "NULL".
[TRACE] 2024-11-07 10:12:26.2754 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADTTE"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:26.2834 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADTTE"; select: "NULL".
[TRACE] 2024-11-07 10:12:26.2884 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADTTE"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:26.2960 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADSL"; select: "AGE".
[TRACE] 2024-11-07 10:12:26.3008 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADSL"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:26.4217 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_filter_overview@1 updating counts
[TRACE] 2024-11-07 10:12:26.4250 pid:25200 token:[3feda1ab] teal.slice FilteredDataset$srv_filter_overview initialized
[TRACE] 2024-11-07 10:12:26.4298 pid:25200 token:[3feda1ab] teal.slice FilteredDataset$srv_filter_overview initialized
[TRACE] 2024-11-07 10:12:26.4375 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_filter_overview@1 updated counts
[TRACE] 2024-11-07 10:12:26.5540 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADTTE"; select: "AVAL".
[TRACE] 2024-11-07 10:12:26.5590 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADTTE"; select: "CNSR".
[TRACE] 2024-11-07 10:12:26.5737 pid:25200 token:[3feda1ab] teal.transform merge_datasets called with: "ADSL, ADTTE" datasets; "arm_var, paramcd, strata_var, aval_var, cnsr_var, cov_var" selectors; "dplyr::inner_join" merge function.
[TRACE] 2024-11-07 10:12:26.5772 pid:25200 token:[3feda1ab] teal.transform merge_selectors called with: "arm_var, paramcd, strata_var, aval_var, cnsr_var, cov_var" selectors.
[TRACE] 2024-11-07 10:12:26.5811 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call_data called with: "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:26.5852 pid:25200 token:[3feda1ab] teal.transform get_merge_key_grid called with: "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:26.5898 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "arm_var, arm_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:26.5926 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "arm_var" selector.
[TRACE] 2024-11-07 10:12:26.5957 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:26.6035 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "arm_var, paramcd" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:26.6064 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:26.6129 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "arm_var, aval_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:26.6166 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:26.6239 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "paramcd, arm_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:26.6267 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:26.6351 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "paramcd, paramcd" selectors; "STUDYID, USUBJID, PARAMCD" keys.
[TRACE] 2024-11-07 10:12:26.6384 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "paramcd" selector.
[TRACE] 2024-11-07 10:12:26.6408 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD" merge keys.
[TRACE] 2024-11-07 10:12:26.6483 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "paramcd, aval_var" selectors; "STUDYID, USUBJID, PARAMCD" keys.
[TRACE] 2024-11-07 10:12:26.6517 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "paramcd" selector.
[TRACE] 2024-11-07 10:12:26.6547 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD" merge keys.
[TRACE] 2024-11-07 10:12:26.6622 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "aval_var, arm_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:26.6653 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:26.6727 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "aval_var, paramcd" selectors; "STUDYID, USUBJID, PARAMCD" keys.
[TRACE] 2024-11-07 10:12:26.6755 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "aval_var" selector.
[TRACE] 2024-11-07 10:12:26.6783 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD" merge keys.
[TRACE] 2024-11-07 10:12:26.6870 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "aval_var, aval_var" selectors; "STUDYID, USUBJID, PARAMCD" keys.
[TRACE] 2024-11-07 10:12:26.6902 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "aval_var" selector.
[TRACE] 2024-11-07 10:12:26.6933 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD" merge keys.
[TRACE] 2024-11-07 10:12:26.7054 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call called with: "ADSL, ADTTE" datasets; "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:26.7092 pid:25200 token:[3feda1ab] teal.transform get_filter_call called with: "ADSL" dataset; "" filters.
[TRACE] 2024-11-07 10:12:26.7123 pid:25200 token:[3feda1ab] teal.transform get_select_call called with: "STUDYID, USUBJID, ARM, STRATA1, AGE" columns.
[TRACE] 2024-11-07 10:12:26.7155 pid:25200 token:[3feda1ab] teal.transform get_rename_call called with: "arm_var" selector; "ARM, STRATA1, AGE" renamed columns.
[TRACE] 2024-11-07 10:12:26.7190 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call called with: "ADSL, ADTTE" datasets; "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:26.7220 pid:25200 token:[3feda1ab] teal.transform get_filter_call called with: "ADTTE" dataset; "PARAMCD" filters.
[TRACE] 2024-11-07 10:12:26.7323 pid:25200 token:[3feda1ab] teal.transform get_select_call called with: "STUDYID, USUBJID, PARAMCD" columns.
[TRACE] 2024-11-07 10:12:26.7355 pid:25200 token:[3feda1ab] teal.transform get_rename_call called with: "paramcd" selector; "" renamed columns.
[TRACE] 2024-11-07 10:12:26.7388 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call called with: "ADSL, ADTTE" datasets; "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:26.7427 pid:25200 token:[3feda1ab] teal.transform get_filter_call called with: "ADTTE" dataset; "" filters.
[TRACE] 2024-11-07 10:12:26.7454 pid:25200 token:[3feda1ab] teal.transform get_select_call called with: "STUDYID, USUBJID, PARAMCD, AVAL, CNSR" columns.
[TRACE] 2024-11-07 10:12:26.7486 pid:25200 token:[3feda1ab] teal.transform get_rename_call called with: "aval_var" selector; "AVAL, CNSR" renamed columns.
[TRACE] 2024-11-07 10:12:26.7528 pid:25200 token:[3feda1ab] teal.transform get_merge_call called with: "arm_var, paramcd, aval_var" selectors; "dplyr::inner_join" merge function.
[TRACE] 2024-11-07 10:12:26.7576 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i called with "arm_var, paramcd, aval_var" selectors; idx = 2L.
[TRACE] 2024-11-07 10:12:26.7600 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i returns "STUDYID USUBJID" unique keys.
[TRACE] 2024-11-07 10:12:26.7628 pid:25200 token:[3feda1ab] teal.transform parse_merge_key_i called with "STUDYID USUBJID" keys.
[TRACE] 2024-11-07 10:12:26.7662 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i called with "arm_var, paramcd, aval_var" selectors; idx = 3L.
[TRACE] 2024-11-07 10:12:26.7699 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i returns "STUDYID USUBJID PARAMCD" unique keys.
[TRACE] 2024-11-07 10:12:26.7758 pid:25200 token:[3feda1ab] teal.transform parse_merge_key_i called with "STUDYID USUBJID PARAMCD" keys.
[TRACE] 2024-11-07 10:12:26.7840 pid:25200 token:[3feda1ab] teal.transform get_relabel_cols called with: "arm_var, paramcd, strata_var, aval_var, cnsr_var, cov_var" columns_source.
[TRACE] 2024-11-07 10:12:26.7923 pid:25200 token:[3feda1ab] teal.transform get_anl_relabel_call called with: "arm_var, paramcd, strata_var, aval_var, cnsr_var, cov_var" columns_source; "ANL" merged dataset.
[TRACE] 2024-11-07 10:12:26.8069 pid:25200 token:[3feda1ab] teal.transform get_relabel_call called with: "Description of Planned Arm Parameter Code Stratification Factor 1 Analysis Value Censor Age" labels.
[TRACE] 2024-11-07 10:12:26.8095 pid:25200 token:[3feda1ab] teal.transform merge_datasets merge code executed resulting in "ANL" dataset.
[TRACE] 2024-11-07 10:12:33.1478 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_filter_overview@1 updating counts
[TRACE] 2024-11-07 10:12:33.1507 pid:25200 token:[3feda1ab] teal.slice FilteredDataset$srv_filter_overview initialized
[TRACE] 2024-11-07 10:12:33.1571 pid:25200 token:[3feda1ab] teal.slice FilteredDataset$srv_filter_overview initialized
[TRACE] 2024-11-07 10:12:33.1648 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_filter_overview@1 updated counts
[TRACE] 2024-11-07 10:12:33.2452 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:12:33.2479 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:12:33.2580 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:12:33.2612 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADTTE"
[TRACE] 2024-11-07 10:12:33.2643 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:12:33.2680 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADTTE"
[TRACE] 2024-11-07 10:12:33.2976 pid:25200 token:[3feda1ab] teal.transform data_extract_multiple_srv.list initialized with dataset: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:33.3115 pid:25200 token:[3feda1ab] teal.transform merge_expression_srv initialized with: "ADSL, ADTTE" datasets.
[TRACE] 2024-11-07 10:12:33.3259 pid:25200 token:[3feda1ab] teal.transform merge_expression_module called with: "ADSL, ADTTE" datasets.
[TRACE] 2024-11-07 10:12:33.3298 pid:25200 token:[3feda1ab] teal.transform data_extract_multiple_srv.list initialized with dataset: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:33.3385 pid:25200 token:[3feda1ab] teal.transform merge_expression_srv initialized with: "ADSL, ADTTE" datasets.
[TRACE] 2024-11-07 10:12:33.4497 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:33.4550 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADSL".
[TRACE] 2024-11-07 10:12:33.4692 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADSL" dataset.
[TRACE] 2024-11-07 10:12:33.4822 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:33.4890 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADTTE".
[TRACE] 2024-11-07 10:12:33.4935 pid:25200 token:[3feda1ab] teal.transform data_extract_filter_srv initialized with: "ADTTE" dataset.
[TRACE] 2024-11-07 10:12:33.5107 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADTTE" dataset.
[TRACE] 2024-11-07 10:12:33.5250 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:33.5293 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADSL".
[TRACE] 2024-11-07 10:12:33.5465 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADSL" dataset.
[TRACE] 2024-11-07 10:12:33.5602 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:33.5656 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADSL".
[TRACE] 2024-11-07 10:12:33.5799 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADSL" dataset.
[TRACE] 2024-11-07 10:12:33.5929 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:33.5979 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADTTE".
[TRACE] 2024-11-07 10:12:33.6322 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADTTE" dataset.
[TRACE] 2024-11-07 10:12:33.6479 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:33.6620 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADTTE".
[TRACE] 2024-11-07 10:12:33.6937 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADTTE" dataset.
[TRACE] 2024-11-07 10:12:33.7093 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:33.7138 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADTTE".
[TRACE] 2024-11-07 10:12:33.7317 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADTTE" dataset.
[TRACE] 2024-11-07 10:12:33.7485 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADSL"; select: "ARM".
[TRACE] 2024-11-07 10:12:33.7533 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADSL"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:33.7609 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@1 dataname: "ADTTE"; filter vars: "PARAMCD"; filter values: "OS"
[TRACE] 2024-11-07 10:12:33.7666 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADTTE"; select: "PARAMCD".
[TRACE] 2024-11-07 10:12:33.7740 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADTTE"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:33.7819 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADSL"; select: "AGEGR1".
[TRACE] 2024-11-07 10:12:33.7902 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADSL"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:33.7981 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADSL"; select: "STRATA1".
[TRACE] 2024-11-07 10:12:33.8036 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADSL"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:33.8109 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADTTE"; select: "NULL".
[TRACE] 2024-11-07 10:12:33.8156 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADTTE"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:33.8253 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADTTE"; select: "NULL".
[TRACE] 2024-11-07 10:12:33.8294 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADTTE"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:33.8407 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADTTE"; select: "NULL".
[TRACE] 2024-11-07 10:12:33.8450 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADTTE"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:33.9765 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADTTE"; select: "AVAL".
[TRACE] 2024-11-07 10:12:33.9819 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADTTE"; select: "CNSR".
[TRACE] 2024-11-07 10:12:33.9881 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADTTE"; select: "AVALU".
[TRACE] 2024-11-07 10:12:34.0017 pid:25200 token:[3feda1ab] teal.transform merge_datasets called with: "ADSL, ADTTE" datasets; "arm_var, paramcd, subgroup_var, strata_var, aval_var, cnsr_var, time_unit_var" selectors; "dplyr::inner_join" merge function.
[TRACE] 2024-11-07 10:12:34.0053 pid:25200 token:[3feda1ab] teal.transform merge_selectors called with: "arm_var, paramcd, subgroup_var, strata_var, aval_var, cnsr_var, time_unit_var" selectors.
[TRACE] 2024-11-07 10:12:34.0091 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call_data called with: "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:34.0120 pid:25200 token:[3feda1ab] teal.transform get_merge_key_grid called with: "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:34.0168 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "arm_var, arm_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:34.0203 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "arm_var" selector.
[TRACE] 2024-11-07 10:12:34.0228 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:34.0428 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "arm_var, paramcd" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:34.0461 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:34.0563 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "arm_var, aval_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:34.0594 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:34.0665 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "paramcd, arm_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:34.0699 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:34.0771 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "paramcd, paramcd" selectors; "STUDYID, USUBJID, PARAMCD" keys.
[TRACE] 2024-11-07 10:12:34.0800 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "paramcd" selector.
[TRACE] 2024-11-07 10:12:34.0833 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD" merge keys.
[TRACE] 2024-11-07 10:12:34.0915 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "paramcd, aval_var" selectors; "STUDYID, USUBJID, PARAMCD" keys.
[TRACE] 2024-11-07 10:12:34.0943 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "paramcd" selector.
[TRACE] 2024-11-07 10:12:34.0972 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD" merge keys.
[TRACE] 2024-11-07 10:12:34.1063 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "aval_var, arm_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:34.1096 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:34.1214 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "aval_var, paramcd" selectors; "STUDYID, USUBJID, PARAMCD" keys.
[TRACE] 2024-11-07 10:12:34.1245 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "aval_var" selector.
[TRACE] 2024-11-07 10:12:34.1269 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD" merge keys.
[TRACE] 2024-11-07 10:12:34.1353 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "aval_var, aval_var" selectors; "STUDYID, USUBJID, PARAMCD" keys.
[TRACE] 2024-11-07 10:12:34.1401 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "aval_var" selector.
[TRACE] 2024-11-07 10:12:34.1429 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD" merge keys.
[TRACE] 2024-11-07 10:12:34.1564 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call called with: "ADSL, ADTTE" datasets; "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:34.1594 pid:25200 token:[3feda1ab] teal.transform get_filter_call called with: "ADSL" dataset; "" filters.
[TRACE] 2024-11-07 10:12:34.1621 pid:25200 token:[3feda1ab] teal.transform get_select_call called with: "STUDYID, USUBJID, ARM, AGEGR1, STRATA1" columns.
[TRACE] 2024-11-07 10:12:34.1657 pid:25200 token:[3feda1ab] teal.transform get_rename_call called with: "arm_var" selector; "ARM, AGEGR1, STRATA1" renamed columns.
[TRACE] 2024-11-07 10:12:34.1707 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call called with: "ADSL, ADTTE" datasets; "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:34.1742 pid:25200 token:[3feda1ab] teal.transform get_filter_call called with: "ADTTE" dataset; "PARAMCD" filters.
[TRACE] 2024-11-07 10:12:34.1846 pid:25200 token:[3feda1ab] teal.transform get_select_call called with: "STUDYID, USUBJID, PARAMCD" columns.
[TRACE] 2024-11-07 10:12:34.1880 pid:25200 token:[3feda1ab] teal.transform get_rename_call called with: "paramcd" selector; "" renamed columns.
[TRACE] 2024-11-07 10:12:34.1907 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call called with: "ADSL, ADTTE" datasets; "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:34.1938 pid:25200 token:[3feda1ab] teal.transform get_filter_call called with: "ADTTE" dataset; "" filters.
[TRACE] 2024-11-07 10:12:34.1974 pid:25200 token:[3feda1ab] teal.transform get_select_call called with: "STUDYID, USUBJID, PARAMCD, AVAL, CNSR, AVALU" columns.
[TRACE] 2024-11-07 10:12:34.2026 pid:25200 token:[3feda1ab] teal.transform get_rename_call called with: "aval_var" selector; "AVAL, CNSR, AVALU" renamed columns.
[TRACE] 2024-11-07 10:12:34.2062 pid:25200 token:[3feda1ab] teal.transform get_merge_call called with: "arm_var, paramcd, aval_var" selectors; "dplyr::inner_join" merge function.
[TRACE] 2024-11-07 10:12:34.2089 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i called with "arm_var, paramcd, aval_var" selectors; idx = 2L.
[TRACE] 2024-11-07 10:12:34.2115 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i returns "STUDYID USUBJID" unique keys.
[TRACE] 2024-11-07 10:12:34.2148 pid:25200 token:[3feda1ab] teal.transform parse_merge_key_i called with "STUDYID USUBJID" keys.
[TRACE] 2024-11-07 10:12:34.2200 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i called with "arm_var, paramcd, aval_var" selectors; idx = 3L.
[TRACE] 2024-11-07 10:12:34.2228 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i returns "STUDYID USUBJID PARAMCD" unique keys.
[TRACE] 2024-11-07 10:12:34.2263 pid:25200 token:[3feda1ab] teal.transform parse_merge_key_i called with "STUDYID USUBJID PARAMCD" keys.
[TRACE] 2024-11-07 10:12:34.2293 pid:25200 token:[3feda1ab] teal.transform get_relabel_cols called with: "arm_var, paramcd, subgroup_var, strata_var, aval_var, cnsr_var, time_unit_var" columns_source.
[TRACE] 2024-11-07 10:12:34.2401 pid:25200 token:[3feda1ab] teal.transform get_anl_relabel_call called with: "arm_var, paramcd, subgroup_var, strata_var, aval_var, cnsr_var, time_unit_var" columns_source; "ANL" merged dataset.
[TRACE] 2024-11-07 10:12:34.2584 pid:25200 token:[3feda1ab] teal.transform get_relabel_call called with: "Description of Planned Arm Parameter Code Age Group Stratification Factor 1 Analysis Value Censor Analysis Value Unit" labels.
[TRACE] 2024-11-07 10:12:34.2623 pid:25200 token:[3feda1ab] teal.transform merge_datasets merge code executed resulting in "ANL" dataset.
[TRACE] 2024-11-07 10:12:34.2873 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:34.2998 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADSL".
[TRACE] 2024-11-07 10:12:34.3174 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADSL" dataset.
[TRACE] 2024-11-07 10:12:34.3323 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:34.3450 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADSL".
[TRACE] 2024-11-07 10:12:34.3654 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADSL" dataset.
[TRACE] 2024-11-07 10:12:34.3837 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADTTE".
[TRACE] 2024-11-07 10:12:34.3951 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADSL".
[TRACE] 2024-11-07 10:12:34.4101 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADSL" dataset.
[TRACE] 2024-11-07 10:12:34.4248 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADSL"; select: "ARM".
[TRACE] 2024-11-07 10:12:34.4284 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADSL"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:34.4356 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADSL"; select: "AGEGR1".
[TRACE] 2024-11-07 10:12:34.4394 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADSL"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:34.4447 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADSL"; select: "STRATA1".
[TRACE] 2024-11-07 10:12:34.4480 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADSL"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:34.4519 pid:25200 token:[3feda1ab] teal.transform merge_datasets called with: "ADSL, ADTTE" datasets; "arm_var, subgroup_var, strata_var" selectors; "dplyr::full_join" merge function.
[TRACE] 2024-11-07 10:12:34.4555 pid:25200 token:[3feda1ab] teal.transform merge_selectors called with: "arm_var, subgroup_var, strata_var" selectors.
[TRACE] 2024-11-07 10:12:34.4591 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call_data called with: "arm_var" selectors.
[TRACE] 2024-11-07 10:12:34.4621 pid:25200 token:[3feda1ab] teal.transform get_merge_key_grid called with: "arm_var" selectors.
[TRACE] 2024-11-07 10:12:34.4672 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "arm_var, arm_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:34.4710 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "arm_var" selector.
[TRACE] 2024-11-07 10:12:34.4736 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:34.4763 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call called with: "ADSL, ADTTE" datasets; "arm_var" selectors.
[TRACE] 2024-11-07 10:12:34.4796 pid:25200 token:[3feda1ab] teal.transform get_filter_call called with: "ADSL" dataset; "" filters.
[TRACE] 2024-11-07 10:12:34.4837 pid:25200 token:[3feda1ab] teal.transform get_select_call called with: "STUDYID, USUBJID, ARM, AGEGR1, STRATA1" columns.
[TRACE] 2024-11-07 10:12:34.4886 pid:25200 token:[3feda1ab] teal.transform get_merge_call called with: "arm_var" selectors; "dplyr::full_join" merge function.
[TRACE] 2024-11-07 10:12:34.5048 pid:25200 token:[3feda1ab] teal.transform get_relabel_cols called with: "arm_var, subgroup_var, strata_var" columns_source.
[TRACE] 2024-11-07 10:12:34.5074 pid:25200 token:[3feda1ab] teal.transform get_anl_relabel_call called with: "arm_var, subgroup_var, strata_var" columns_source; "ANL_ADSL" merged dataset.
[TRACE] 2024-11-07 10:12:34.5134 pid:25200 token:[3feda1ab] teal.transform get_relabel_call called with: "Description of Planned Arm Age Group Stratification Factor 1" labels.
[TRACE] 2024-11-07 10:12:34.5165 pid:25200 token:[3feda1ab] teal.transform merge_datasets merge code executed resulting in "ANL_ADSL" dataset.
[TRACE] 2024-11-07 10:12:37.7829 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_filter_overview@1 updating counts
[TRACE] 2024-11-07 10:12:37.7865 pid:25200 token:[3feda1ab] teal.slice FilteredDataset$srv_filter_overview initialized
[TRACE] 2024-11-07 10:12:37.7915 pid:25200 token:[3feda1ab] teal.slice FilteredDataset$srv_filter_overview initialized
[TRACE] 2024-11-07 10:12:37.7970 pid:25200 token:[3feda1ab] teal.slice FilteredData$srv_filter_overview@1 updated counts
[TRACE] 2024-11-07 10:12:37.8707 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:12:37.8731 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:12:37.8783 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADSL"
[TRACE] 2024-11-07 10:12:37.8817 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADRS"
[TRACE] 2024-11-07 10:12:37.8853 pid:25200 token:[3feda1ab] teal.slice FilterStates$get_call initializing
[TRACE] 2024-11-07 10:12:37.8890 pid:25200 token:[3feda1ab] teal.slice DataframeFilteredDataset$get_call initializing for dataname: "ADRS"
[TRACE] 2024-11-07 10:12:37.9119 pid:25200 token:[3feda1ab] teal.transform data_extract_multiple_srv.list initialized with dataset: "ADSL, ADRS".
[TRACE] 2024-11-07 10:12:37.9391 pid:25200 token:[3feda1ab] teal.transform merge_expression_srv initialized with: "ADSL, ADRS" datasets.
[TRACE] 2024-11-07 10:12:37.9509 pid:25200 token:[3feda1ab] teal.transform merge_expression_module called with: "ADSL, ADRS" datasets.
[TRACE] 2024-11-07 10:12:37.9554 pid:25200 token:[3feda1ab] teal.transform data_extract_multiple_srv.list initialized with dataset: "ADSL, ADRS".
[TRACE] 2024-11-07 10:12:37.9611 pid:25200 token:[3feda1ab] teal.transform merge_expression_srv initialized with: "ADSL, ADRS" datasets.
[TRACE] 2024-11-07 10:12:38.0381 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADRS".
[TRACE] 2024-11-07 10:12:38.0424 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADSL".
[TRACE] 2024-11-07 10:12:38.0575 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADSL" dataset.
[TRACE] 2024-11-07 10:12:38.0725 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADRS".
[TRACE] 2024-11-07 10:12:38.0771 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADRS".
[TRACE] 2024-11-07 10:12:38.0810 pid:25200 token:[3feda1ab] teal.transform data_extract_filter_srv initialized with: "ADRS" dataset.
[TRACE] 2024-11-07 10:12:38.0960 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADRS" dataset.
[TRACE] 2024-11-07 10:12:38.1091 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADRS".
[TRACE] 2024-11-07 10:12:38.1142 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADSL".
[TRACE] 2024-11-07 10:12:38.1403 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADSL" dataset.
[TRACE] 2024-11-07 10:12:38.1529 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADRS".
[TRACE] 2024-11-07 10:12:38.1573 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADRS".
[TRACE] 2024-11-07 10:12:38.1757 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADRS" dataset.
[TRACE] 2024-11-07 10:12:38.1917 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADSL"; select: "ARM".
[TRACE] 2024-11-07 10:12:38.1974 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADSL"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:38.2045 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@1 dataname: "ADRS"; filter vars: "PARAMCD"; filter values: "BESRSPI"
[TRACE] 2024-11-07 10:12:38.2096 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADRS"; select: "PARAMCD".
[TRACE] 2024-11-07 10:12:38.2135 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADRS"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:38.2204 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADSL"; select: "STRATA1".
[TRACE] 2024-11-07 10:12:38.2242 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADSL"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:38.2307 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADRS"; select: "NULL".
[TRACE] 2024-11-07 10:12:38.2358 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADRS"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:38.2397 pid:25200 token:[3feda1ab] teal.transform merge_datasets called with: "ADSL, ADRS" datasets; "arm_var, paramcd, strata_var, aval_var" selectors; "dplyr::inner_join" merge function.
[TRACE] 2024-11-07 10:12:38.2430 pid:25200 token:[3feda1ab] teal.transform merge_selectors called with: "arm_var, paramcd, strata_var, aval_var" selectors.
[TRACE] 2024-11-07 10:12:38.2458 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call_data called with: "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:38.2483 pid:25200 token:[3feda1ab] teal.transform get_merge_key_grid called with: "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:38.2534 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "arm_var, arm_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:38.2568 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "arm_var" selector.
[TRACE] 2024-11-07 10:12:38.2592 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:38.2659 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "arm_var, paramcd" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:38.2689 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:38.2766 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "arm_var, aval_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:38.2802 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:38.2872 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "paramcd, arm_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:38.2903 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:38.2968 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "paramcd, paramcd" selectors; "STUDYID, USUBJID, PARAMCD, AVISIT" keys.
[TRACE] 2024-11-07 10:12:38.2998 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "paramcd" selector.
[TRACE] 2024-11-07 10:12:38.3033 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD, AVISIT" merge keys.
[TRACE] 2024-11-07 10:12:38.3112 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "paramcd, aval_var" selectors; "STUDYID, USUBJID, PARAMCD, AVISIT" keys.
[TRACE] 2024-11-07 10:12:38.3139 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "paramcd" selector.
[TRACE] 2024-11-07 10:12:38.3164 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD, AVISIT" merge keys.
[TRACE] 2024-11-07 10:12:38.3245 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "aval_var, arm_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:38.3274 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:38.3343 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "aval_var, paramcd" selectors; "STUDYID, USUBJID, PARAMCD, AVISIT" keys.
[TRACE] 2024-11-07 10:12:38.3380 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "aval_var" selector.
[TRACE] 2024-11-07 10:12:38.3403 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD, AVISIT" merge keys.
[TRACE] 2024-11-07 10:12:38.3465 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "aval_var, aval_var" selectors; "STUDYID, USUBJID, PARAMCD, AVISIT" keys.
[TRACE] 2024-11-07 10:12:38.3494 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "aval_var" selector.
[TRACE] 2024-11-07 10:12:38.3548 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD, AVISIT" merge keys.
[TRACE] 2024-11-07 10:12:38.3656 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call called with: "ADSL, ADRS" datasets; "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:38.3707 pid:25200 token:[3feda1ab] teal.transform get_filter_call called with: "ADSL" dataset; "" filters.
[TRACE] 2024-11-07 10:12:38.3737 pid:25200 token:[3feda1ab] teal.transform get_select_call called with: "STUDYID, USUBJID, ARM, STRATA1" columns.
[TRACE] 2024-11-07 10:12:38.3762 pid:25200 token:[3feda1ab] teal.transform get_rename_call called with: "arm_var" selector; "ARM, STRATA1" renamed columns.
[TRACE] 2024-11-07 10:12:38.3787 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call called with: "ADSL, ADRS" datasets; "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:38.3815 pid:25200 token:[3feda1ab] teal.transform get_filter_call called with: "ADRS" dataset; "PARAMCD" filters.
[TRACE] 2024-11-07 10:12:38.3891 pid:25200 token:[3feda1ab] teal.transform get_select_call called with: "STUDYID, USUBJID, PARAMCD, AVISIT" columns.
[TRACE] 2024-11-07 10:12:38.3917 pid:25200 token:[3feda1ab] teal.transform get_rename_call called with: "paramcd" selector; "" renamed columns.
[TRACE] 2024-11-07 10:12:38.3943 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call called with: "ADSL, ADRS" datasets; "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:38.3969 pid:25200 token:[3feda1ab] teal.transform get_filter_call called with: "ADRS" dataset; "" filters.
[TRACE] 2024-11-07 10:12:38.3997 pid:25200 token:[3feda1ab] teal.transform get_select_call called with: "STUDYID, USUBJID, PARAMCD, AVISIT" columns.
[TRACE] 2024-11-07 10:12:38.4046 pid:25200 token:[3feda1ab] teal.transform get_rename_call called with: "aval_var" selector; "" renamed columns.
[TRACE] 2024-11-07 10:12:38.4078 pid:25200 token:[3feda1ab] teal.transform get_merge_call called with: "arm_var, paramcd, aval_var" selectors; "dplyr::inner_join" merge function.
[TRACE] 2024-11-07 10:12:38.4103 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i called with "arm_var, paramcd, aval_var" selectors; idx = 2L.
[TRACE] 2024-11-07 10:12:38.4126 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i returns "STUDYID USUBJID" unique keys.
[TRACE] 2024-11-07 10:12:38.4147 pid:25200 token:[3feda1ab] teal.transform parse_merge_key_i called with "STUDYID USUBJID" keys.
[TRACE] 2024-11-07 10:12:38.4194 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i called with "arm_var, paramcd, aval_var" selectors; idx = 3L.
[TRACE] 2024-11-07 10:12:38.4221 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i returns "STUDYID USUBJID PARAMCD AVISIT" unique keys.
[TRACE] 2024-11-07 10:12:38.4243 pid:25200 token:[3feda1ab] teal.transform parse_merge_key_i called with "STUDYID USUBJID PARAMCD AVISIT" keys.
[TRACE] 2024-11-07 10:12:38.4268 pid:25200 token:[3feda1ab] teal.transform get_relabel_cols called with: "arm_var, paramcd, strata_var, aval_var" columns_source.
[TRACE] 2024-11-07 10:12:38.4289 pid:25200 token:[3feda1ab] teal.transform get_anl_relabel_call called with: "arm_var, paramcd, strata_var, aval_var" columns_source; "ANL" merged dataset.
[TRACE] 2024-11-07 10:12:38.4367 pid:25200 token:[3feda1ab] teal.transform get_relabel_call called with: "Description of Planned Arm Parameter Code Stratification Factor 1" labels.
[TRACE] 2024-11-07 10:12:38.4401 pid:25200 token:[3feda1ab] teal.transform merge_datasets merge code executed resulting in "ANL" dataset.
[TRACE] 2024-11-07 10:12:38.4559 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADRS".
[TRACE] 2024-11-07 10:12:38.4662 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADSL".
[TRACE] 2024-11-07 10:12:38.5124 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADSL" dataset.
[TRACE] 2024-11-07 10:12:38.5325 pid:25200 token:[3feda1ab] teal.transform data_extract_srv.list initialized with datasets: "ADSL, ADRS".
[TRACE] 2024-11-07 10:12:38.5443 pid:25200 token:[3feda1ab] teal.transform data_extract_single_srv initialized with dataset: "ADSL".
[TRACE] 2024-11-07 10:12:38.5642 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv initialized with: "ADSL" dataset.
[TRACE] 2024-11-07 10:12:38.5800 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADSL"; select: "ARM".
[TRACE] 2024-11-07 10:12:38.5846 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADSL"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:38.5916 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADSL"; select: "STRATA1".
[TRACE] 2024-11-07 10:12:38.5952 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@3 dataname: "ADSL"; reshape: "FALSE".
[TRACE] 2024-11-07 10:12:38.5985 pid:25200 token:[3feda1ab] teal.transform merge_datasets called with: "ADSL, ADRS" datasets; "arm_var, strata_var" selectors; "dplyr::full_join" merge function.
[TRACE] 2024-11-07 10:12:38.6023 pid:25200 token:[3feda1ab] teal.transform merge_selectors called with: "arm_var, strata_var" selectors.
[TRACE] 2024-11-07 10:12:38.6058 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call_data called with: "arm_var" selectors.
[TRACE] 2024-11-07 10:12:38.6087 pid:25200 token:[3feda1ab] teal.transform get_merge_key_grid called with: "arm_var" selectors.
[TRACE] 2024-11-07 10:12:38.6125 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "arm_var, arm_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:38.6151 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "arm_var" selector.
[TRACE] 2024-11-07 10:12:38.6182 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:38.6223 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call called with: "ADSL, ADRS" datasets; "arm_var" selectors.
[TRACE] 2024-11-07 10:12:38.6252 pid:25200 token:[3feda1ab] teal.transform get_filter_call called with: "ADSL" dataset; "" filters.
[TRACE] 2024-11-07 10:12:38.6276 pid:25200 token:[3feda1ab] teal.transform get_select_call called with: "STUDYID, USUBJID, ARM, STRATA1" columns.
[TRACE] 2024-11-07 10:12:38.6303 pid:25200 token:[3feda1ab] teal.transform get_merge_call called with: "arm_var" selectors; "dplyr::full_join" merge function.
[TRACE] 2024-11-07 10:12:38.6330 pid:25200 token:[3feda1ab] teal.transform get_relabel_cols called with: "arm_var, strata_var" columns_source.
[TRACE] 2024-11-07 10:12:38.6361 pid:25200 token:[3feda1ab] teal.transform get_anl_relabel_call called with: "arm_var, strata_var" columns_source; "ANL_ADSL" merged dataset.
[TRACE] 2024-11-07 10:12:38.6417 pid:25200 token:[3feda1ab] teal.transform get_relabel_call called with: "Description of Planned Arm Stratification Factor 1" labels.
[TRACE] 2024-11-07 10:12:38.6442 pid:25200 token:[3feda1ab] teal.transform merge_datasets merge code executed resulting in "ANL_ADSL" dataset.
[TRACE] 2024-11-07 10:12:38.8940 pid:25200 token:[3feda1ab] teal.transform data_extract_read_srv@2 dataname: "ADRS"; select: "AVALC".
[TRACE] 2024-11-07 10:12:38.9312 pid:25200 token:[3feda1ab] teal.transform merge_datasets called with: "ADSL, ADRS" datasets; "arm_var, paramcd, strata_var, aval_var" selectors; "dplyr::inner_join" merge function.
[TRACE] 2024-11-07 10:12:38.9359 pid:25200 token:[3feda1ab] teal.transform merge_selectors called with: "arm_var, paramcd, strata_var, aval_var" selectors.
[TRACE] 2024-11-07 10:12:38.9402 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call_data called with: "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:38.9438 pid:25200 token:[3feda1ab] teal.transform get_merge_key_grid called with: "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:38.9477 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "arm_var, arm_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:38.9509 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "arm_var" selector.
[TRACE] 2024-11-07 10:12:38.9544 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:38.9610 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "arm_var, paramcd" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:38.9637 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:38.9721 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "arm_var, aval_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:38.9756 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:38.9824 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "paramcd, arm_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:38.9870 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:38.9938 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "paramcd, paramcd" selectors; "STUDYID, USUBJID, PARAMCD, AVISIT" keys.
[TRACE] 2024-11-07 10:12:38.9965 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "paramcd" selector.
[TRACE] 2024-11-07 10:12:38.9989 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD, AVISIT" merge keys.
[TRACE] 2024-11-07 10:12:39.0076 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "paramcd, aval_var" selectors; "STUDYID, USUBJID, PARAMCD, AVISIT" keys.
[TRACE] 2024-11-07 10:12:39.0103 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "paramcd" selector.
[TRACE] 2024-11-07 10:12:39.0126 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD, AVISIT" merge keys.
[TRACE] 2024-11-07 10:12:39.0196 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "aval_var, arm_var" selectors; "STUDYID, USUBJID" keys.
[TRACE] 2024-11-07 10:12:39.0224 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID" merge keys.
[TRACE] 2024-11-07 10:12:39.0288 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "aval_var, paramcd" selectors; "STUDYID, USUBJID, PARAMCD, AVISIT" keys.
[TRACE] 2024-11-07 10:12:39.0321 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "aval_var" selector.
[TRACE] 2024-11-07 10:12:39.0355 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD, AVISIT" merge keys.
[TRACE] 2024-11-07 10:12:39.0430 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair called with: "aval_var, aval_var" selectors; "STUDYID, USUBJID, PARAMCD, AVISIT" keys.
[TRACE] 2024-11-07 10:12:39.0457 pid:25200 token:[3feda1ab] teal.transform get_dropped_filters called with "aval_var" selector.
[TRACE] 2024-11-07 10:12:39.0484 pid:25200 token:[3feda1ab] teal.transform get_merge_key_pair returns "STUDYID, USUBJID, PARAMCD, AVISIT" merge keys.
[TRACE] 2024-11-07 10:12:39.0592 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call called with: "ADSL, ADRS" datasets; "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:39.0624 pid:25200 token:[3feda1ab] teal.transform get_filter_call called with: "ADSL" dataset; "" filters.
[TRACE] 2024-11-07 10:12:39.0648 pid:25200 token:[3feda1ab] teal.transform get_select_call called with: "STUDYID, USUBJID, ARM, STRATA1" columns.
[TRACE] 2024-11-07 10:12:39.0680 pid:25200 token:[3feda1ab] teal.transform get_rename_call called with: "arm_var" selector; "ARM, STRATA1" renamed columns.
[TRACE] 2024-11-07 10:12:39.0718 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call called with: "ADSL, ADRS" datasets; "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:39.0746 pid:25200 token:[3feda1ab] teal.transform get_filter_call called with: "ADRS" dataset; "PARAMCD" filters.
[TRACE] 2024-11-07 10:12:39.0799 pid:25200 token:[3feda1ab] teal.transform get_select_call called with: "STUDYID, USUBJID, PARAMCD, AVISIT" columns.
[TRACE] 2024-11-07 10:12:39.0826 pid:25200 token:[3feda1ab] teal.transform get_rename_call called with: "paramcd" selector; "" renamed columns.
[TRACE] 2024-11-07 10:12:39.0877 pid:25200 token:[3feda1ab] teal.transform get_dplyr_call called with: "ADSL, ADRS" datasets; "arm_var, paramcd, aval_var" selectors.
[TRACE] 2024-11-07 10:12:39.0915 pid:25200 token:[3feda1ab] teal.transform get_filter_call called with: "ADRS" dataset; "" filters.
[TRACE] 2024-11-07 10:12:39.0942 pid:25200 token:[3feda1ab] teal.transform get_select_call called with: "STUDYID, USUBJID, PARAMCD, AVISIT, AVALC" columns.
[TRACE] 2024-11-07 10:12:39.0968 pid:25200 token:[3feda1ab] teal.transform get_rename_call called with: "aval_var" selector; "AVALC" renamed columns.
[TRACE] 2024-11-07 10:12:39.1008 pid:25200 token:[3feda1ab] teal.transform get_merge_call called with: "arm_var, paramcd, aval_var" selectors; "dplyr::inner_join" merge function.
[TRACE] 2024-11-07 10:12:39.1044 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i called with "arm_var, paramcd, aval_var" selectors; idx = 2L.
[TRACE] 2024-11-07 10:12:39.1066 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i returns "STUDYID USUBJID" unique keys.
[TRACE] 2024-11-07 10:12:39.1086 pid:25200 token:[3feda1ab] teal.transform parse_merge_key_i called with "STUDYID USUBJID" keys.
[TRACE] 2024-11-07 10:12:39.1113 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i called with "arm_var, paramcd, aval_var" selectors; idx = 3L.
[TRACE] 2024-11-07 10:12:39.1136 pid:25200 token:[3feda1ab] teal.transform get_merge_key_i returns "STUDYID USUBJID PARAMCD AVISIT" unique keys.
[TRACE] 2024-11-07 10:12:39.1158 pid:25200 token:[3feda1ab] teal.transform parse_merge_key_i called with "STUDYID USUBJID PARAMCD AVISIT" keys.
[TRACE] 2024-11-07 10:12:39.1193 pid:25200 token:[3feda1ab] teal.transform get_relabel_cols called with: "arm_var, paramcd, strata_var, aval_var" columns_source.
[TRACE] 2024-11-07 10:12:39.1224 pid:25200 token:[3feda1ab] teal.transform get_anl_relabel_call called with: "arm_var, paramcd, strata_var, aval_var" columns_source; "ANL" merged dataset.
[TRACE] 2024-11-07 10:12:39.1282 pid:25200 token:[3feda1ab] teal.transform get_relabel_call called with: "Description of Planned Arm Parameter Code Stratification Factor 1 Analysis Value (C)" labels.
[TRACE] 2024-11-07 10:12:39.1309 pid:25200 token:[3feda1ab] teal.transform merge_datasets merge code executed resulting in "ANL" dataset.
```

</details>

Pending test with different levels and numeric levels or add tests. 

# teal.log_level = 900

```r
getOption("TEAL.LOG_LAYOUT")
NULL
options(teal.log_level = 900)
```

Package ‘teal.slice’ could not be loaded (loaded from teal.modules.general)

<details>
<summary>LOG</summary>

```r
Loading required package: shiny
Loading required package: ggmosaic
Loading required package: ggplot2
Loading required package: teal
Loading required package: teal.data
Loading required package: teal.code
Loading required package: teal.slice
Error: package or namespace load failed for ‘teal.slice’:
 .onLoad failed in loadNamespace() for 'teal.slice', details:
  call: NULL
  error: .onLoad failed in loadNamespace() for 'teal.logger', details:
  call: value[[3L]](cond)
  error: The log level passed to logger::log_threshold was invalid. Make sure you pass or set the correct log level. See `logger::log_threshold` for more information
Error: package ‘teal.slice’ could not be loaded
```

</details>

# teal.log_level = 900L

```r
getOption("TEAL.LOG_LAYOUT")
NULL
options(teal.log_level = 900L)
```

Same error, numeric values are not accepted even if used as integers:
<details>
<summary>LOG</summary>

```r
library(teal.modules.general)
Loading required package: teal
Loading required package: teal.slice
Error: package or namespace load failed for ‘teal.slice’:
 .onLoad failed in loadNamespace() for 'teal.slice', details:
  call: NULL
  error: .onLoad failed in loadNamespace() for 'teal.logger', details:
  call: value[[3L]](cond)
  error: The log level passed to logger::log_threshold was invalid. Make sure you pass or set the correct log level. See `logger::log_threshold` for more information
Error: package ‘teal.slice’ could not be loaded
```
</details>

**Comment by m7pr** [comment]
```
teal.log_level = "trace"
teal.log_level = 900
teal.log_level = 90L
```

I think we only support those levels

image

this is displayed in the error message that you pasted

image

**Comment by m7pr** [comment]
@llrs-roche with `options(teal.log_level = "TRACE")` you see all information displayed by modules.
With `options(teal.log_level = "DEBUG")`, (one level deeper), you will only see information displayed by `teal.logger::log_shiny_input_changes`.

As the name suggests, it logs input changes, so you need to change the input, to see logs. 
E.g. change the dataset name or YAXIS/XAXIS selectInput.

**Comment by llrs-roche** [comment]
Yes, testing numeric values is too much, but the code I modified includes some code for handling them (and only testing the function worked with numeric values). See this minimal example of what is done inside the function. 

```r
logger::TRACE > 500
[1] TRUE
logger::TRACE > 600
[1] FALSE
```

Perhaps I'm confused but I read in some discussion (cannot find it now) that it might be interesting to have some other levels for reporting in teal framework. 

----

I'll will check again with the DEBUG level, but based on line 52 of this PR (sorry I am not sure how to link to it) I don't think it shouldn't produce logs.

File: R/log_shiny_input_changes.R [hunk 1]
```diff
@@ -44,9 +44,12 @@ log_shiny_input_changes <- function(
...
   stopifnot(is.character(excluded_inputs))
   stopifnot(is.character(excluded_pattern) && length(excluded_pattern) == 1)
-  stopifnot(inherits(session, "session_proxy"))
+  stopifnot(inherits(session, "session_proxy") || inherits(session, "ShinySession"))
 
-  if (logger::TRACE > logger::as.loglevel(get_val("TEAL.LOG_LEVEL", "teal.log_level", "INFO"))) {
+  # Log even if written in lower case or numeric values
+  log_level <- get_val("TEAL.LOG_LEVEL", "teal.log_level", "INFO")
+  if (!is.numeric(log_level)) log_level <- toupper(log_level)
+  if (logger::TRACE > logger::as.loglevel(log_level)) {
```
Comment (llrs-roche) [inline R/log_shiny_input_changes.R:52]: Unless the log_level is TRACE or higher than 700  it won't record anything

**Review by llrs-roche — COMMENTED** [review]
Point to the line about numeric comparison and level required for log_shiny_input_changes to log

File: R/log_shiny_input_changes.R (hunk 1 above)
Comment (m7pr) [reply R/log_shiny_input_changes.R:52]: Yeah, so it records only for DEBUG, ERROR, FATAL, WARN,

Comment (m7pr) [reply R/log_shiny_input_changes.R:52]: But I don't get those numeric values

```r
> logger::as.loglevel(700L)
Error in as.loglevel.integer(700L) : 
  x %in% as.integer(loglevels) is not TRUE
```

**Comment by m7pr** [comment]
> Perhaps I'm confused but I read in some discussion (cannot find it now) that it might be interesting to have some other levels for reporting in teal framework.

We have a couple of different levels. And you can set them with `options(teal.log_level)`. The shiny input changes is the lowest level as this is what we barely want to see. But I think those are visible with `TRACE`. Sorry I pointed you to `DEBUG`.

With `TRACE` you should be able to see changes like in this comment 
https://github.com/insightsengineering/teal.logger/pull/86#issuecomment-2326220057
Can you test on your end?

File: R/log_shiny_input_changes.R (hunk 1 above)
Comment (m7pr) [reply R/log_shiny_input_changes.R:52]:
```r
> logger::as.loglevel(700)
Error in as.loglevel.numeric(700) : 
  x %in% as.integer(loglevels) is not TRUE
```

Comment (m7pr) [reply R/log_shiny_input_changes.R:52]: You are right, `DEBUG` was too high. Sorry

**Comment by llrs-roche** [comment]
I tested again with TRACE level but although I get a lot of logging of level TRACE (which I assumed was already okay) I don't see any "->" on the previous log. The reason, I was mixing libraries and was testing with CRAN versions I assumed this was already an old change available on CRAN but it was a recent change.

Now with the development versions (the easiest way to get them all for me was with `install.packages(pkg, repos = c("https://pharmaverse.r-universe.dev", "https://cloud.r-project.org"))`) I do get the log files with the changes:

```
[TRACE] 2024-11-07 13:13:18.9535 pid:22044 token:[54cf6df3] teal.modules.clinical "teal-teal_modules-mmrm-module" Shiny input change detected in "aval_var-dataset_ADQS_singleextract-select": "AVAL" -> "CHG"
[TRACE] 2024-11-07 13:13:18.9687 pid:22044 token:[54cf6df3] teal.modules.clinical "teal-teal_modules-mmrm-module" Shiny input change detected in "aval_var-dataset_ADQS_singleextract-select_open": TRUE -> FALSE
```

**Review by m7pr — APPROVED** [review]
Amazing, so we get you to run the functionality in real circumstances and the example now actually works. Thanks for the input
